version: "2"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/rufus/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: admin
      POSTGRES_DB: rufus
      POSTGRES_PASSWORD: admin
